<?php
/**
 * Plugin Name: GlobalShopCo Headless
 * Description: Minimal Shopify Storefront API integration for the GlobalShopCo M3 vertical slice.
 * Version: 0.3.2
 */
defined('ABSPATH') || exit;
function gsco_shopify_config(){return ['store_domain'=>defined('GSCO_SHOPIFY_STORE_DOMAIN')?GSCO_SHOPIFY_STORE_DOMAIN:getenv('GSCO_SHOPIFY_STORE_DOMAIN'),'token'=>defined('GSCO_SHOPIFY_STOREFRONT_TOKEN')?GSCO_SHOPIFY_STOREFRONT_TOKEN:getenv('GSCO_SHOPIFY_STOREFRONT_TOKEN'),'api_version'=>defined('GSCO_SHOPIFY_API_VERSION')?GSCO_SHOPIFY_API_VERSION:(getenv('GSCO_SHOPIFY_API_VERSION')?:'2026-07'),'checkout_host'=>defined('GSCO_SHOPIFY_CHECKOUT_HOST')?GSCO_SHOPIFY_CHECKOUT_HOST:getenv('GSCO_SHOPIFY_CHECKOUT_HOST')];}
function gsco_canonical_authority_host($value){if(!is_string($value)||$value===''||$value!==trim($value))return ''; $candidate=strpos($value,'://')===false?'https://'.$value:$value; $parts=parse_url($candidate); if(!is_array($parts)||strtolower($parts['scheme']??'')!=='https'||empty($parts['host'])||isset($parts['user'])||isset($parts['pass'])||isset($parts['port'])||!empty($parts['path'])||isset($parts['query'])||isset($parts['fragment']))return ''; $host=strtolower(rtrim($parts['host'],'.')); return preg_match('/^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$/',$host)?$host:'';}
function gsco_canonical_store_host($value){$host=gsco_canonical_authority_host($value); return $host!==''&&preg_match('/^[a-z0-9][a-z0-9.-]*\.myshopify\.com$/',$host)?$host:'';}
function gsco_validate_checkout_url($u){if(!is_string($u)||trim($u)==='')return new WP_Error('gsco_checkout_url','Shopify checkout is unavailable.'); $p=parse_url($u); if(!is_array($p)||strtolower($p['scheme']??'')!=='https'||empty($p['host'])||isset($p['user'])||isset($p['pass'])||(isset($p['port'])&&(int)$p['port']!==443))return new WP_Error('gsco_checkout_url','Shopify checkout is unavailable.'); $c=gsco_shopify_config(); $configured=!empty($c['checkout_host'])?$c['checkout_host']:$c['store_domain']; $expected=gsco_canonical_authority_host($configured); $actual=strtolower(rtrim($p['host'],'.')); if($expected===''||$actual===''||$actual!==$expected)return new WP_Error('gsco_checkout_host','Shopify checkout is unavailable.'); return $u;}
function gsco_shopify_request($query,$variables=[]){$c=gsco_shopify_config(); if(empty($c['store_domain'])||empty($c['token']))return new WP_Error('gsco_not_configured','Shopify integration is not configured.'); $domain=gsco_canonical_store_host($c['store_domain']); if($domain==='')return new WP_Error('gsco_invalid_store_domain','Shopify store authority is invalid.'); $url='https://'.$domain.'/api/'.rawurlencode($c['api_version']).'/graphql.json'; $r=wp_remote_post($url,['timeout'=>10,'headers'=>['Content-Type'=>'application/json','X-Shopify-Storefront-Access-Token'=>$c['token']],'body'=>wp_json_encode(['query'=>$query,'variables'=>$variables])]); if(is_wp_error($r))return $r; $status=wp_remote_retrieve_response_code($r); $body=json_decode(wp_remote_retrieve_body($r),true); if($status<200||$status>=300||!is_array($body))return new WP_Error('gsco_shopify_http','Shopify request failed.',['status'=>$status]); if(!empty($body['errors']))return new WP_Error('gsco_shopify_graphql','Shopify returned a GraphQL error.'); return $body['data']??[];}
function gsco_get_product($handle){$q='query ProductByHandle($handle: String!) { product(handle: $handle) { id handle title description featuredImage { url altText } variants(first: 1) { nodes { id sku price { amount currencyCode } availableForSale } } } }'; $d=gsco_shopify_request($q,['handle'=>$handle]); if(is_wp_error($d))return $d; $p=$d['product']??null; if($p===null)return null; if(!is_array($p)||!isset($p['id'],$p['handle'])||!is_string($p['id'])||$p['id']===''||!is_string($p['handle'])||$p['handle']!==$handle)return new WP_Error('gsco_product_identity','Shopify product identity is inconsistent.'); return $p;}
function gsco_create_cart_checkout_url($id){if(!is_string($id)||strpos($id,'gid://shopify/ProductVariant/')!==0)return new WP_Error('gsco_invalid_variant','Product variant is unavailable.'); $m='mutation CartCreate($input: CartInput!) { cartCreate(input: $input) { cart { id checkoutUrl } userErrors { field message } } }'; $d=gsco_shopify_request($m,['input'=>['lines'=>[['quantity'=>1,'merchandiseId'=>$id]]]]); if(is_wp_error($d))return $d; $p=$d['cartCreate']??null; if(!is_array($p)||!empty($p['userErrors']))return new WP_Error('gsco_cart_create','Unable to start Shopify checkout.'); return gsco_validate_checkout_url($p['cart']['checkoutUrl']??'');}
function gsco_product_shortcode($atts){$atts=shortcode_atts(['handle'=>'gsco-test-001'],$atts,'gsco_product');$h=sanitize_title($atts['handle']);if(!$h)return '<p>Product unavailable.</p>';$p=gsco_get_product($h);if(is_wp_error($p))return '<p>Product unavailable.</p>';if(!$p)return '<p>Product not found.</p>';$v=$p['variants']['nodes'][0]??null;$html='<article class="gsco-product">';if(!empty($p['featuredImage']['url'])){$alt=esc_attr($p['featuredImage']['altText']?:$p['title']);$html.='<img src="'.esc_url($p['featuredImage']['url']).'" alt="'.$alt.'" loading="lazy">';}$html.='<h2>'.esc_html($p['title']).'</h2><p>'.esc_html($p['description']).'</p>';if($v){$html.='<p><strong>'.esc_html($v['price']['amount'].' '.$v['price']['currencyCode']).'</strong></p>';if(($v['availableForSale']??null)===true){$u=gsco_create_cart_checkout_url($v['id']??'');$html.=is_wp_error($u)?'<p>Checkout temporarily unavailable.</p>':'<p><a class="gsco-buy" href="'.esc_url($u).'" rel="nofollow">Buy via Shopify</a></p>';}else{$html.='<p>Currently unavailable</p>';}}else{$html.='<p>Product variant unavailable.</p>';}$html.='</article>';return $html;} add_shortcode('gsco_product','gsco_product_shortcode');
